site_name: My Docs
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.highlight:
      linenums: true
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - mermaid/mermaid.min.js
theme:
  name: material
nav:
    - Home: index.md
    - About: sample.md
    - Graph: graph.md
    - Sample: sample2.md